"""empty message

Revision ID: 6685452b1c09
Revises: a45de7d7d504
Create Date: 2023-12-04 17:18:02.860915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6685452b1c09'
down_revision = 'a45de7d7d504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('username', type_='unique')

    # ### end Alembic commands ###
